name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet 
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

#  latest image has .NET already installed!
#      - name: Setup .NET environment
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: '2.2.105' 

      - name: Build solution and generate NuGet package
        run: |  
          dotnet pack .\NewRelicSink\NewRelicSink.csproj -c Release -o out

      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Publish NuGet package
        run: | 
          nuget sources add -name "GitHub" -Source https://nuget.pkg.github.com/${{ github.repository }}/index.json -Username jballe -Password ${{ secrets.GITHUB_TOKEN }}
          nuget push out\*.nupkg -Source "GitHub" -SkipDuplicate
